language: go

go:
  - 1.8.x

before_install:
  - curl -LO https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - unzip protoc-3.3.0-linux-x86_64.zip
  - chmod +x bin/protoc

install:
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u google.golang.org/grpc

script:
  - make
  - bin/protoc --go_out=plugins=grpc:. *.proto
