'   CreateVolume +------------+ DeleteVolume
' +------------->|  CREATED   +--------------+
' |              +---+----+---+              |
' |       Controller |    | Controller       v
'+++         Publish |    | Unpublish       +++
'|X|          Volume |    | Volume          | |
'+-+             +---v----+---+             +-+
'                | NODE_READY |
'                +---+----^---+
'               Node |    | Node
'            Publish |    | Unpublish
'             Volume |    | Volume
'                +---v----+---+
'                | PUBLISHED  |
'                +------------+

@startuml
[*] -r-> CREATED: ""CreateVolume""
CREATED -d-> NODE_READY: ""Controller""\n""Publish""\n""Volume""
NODE_READY -d-> PUBLISHED: ""Node""\n""Publish""\n""Volume""
PUBLISHED -u-> NODE_READY: ""Node""\n""Unpublish""\n""Volume""
NODE_READY -u-> CREATED: ""Controller""\n""Unpublish""\n""Volume""
CREATED -r-> [*]: ""DeleteVolume""
@enduml
